[tool.poetry]
name = "repl_python3_botaiogram"
version = "0.1.0"
description = ""
authors = ["vlasovigor <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
aiogram = "^2.12.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
